<a href="https://colab.research.google.com/github/olivia1906-dev/data_science_1/blob/main/31_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Create a Headerless CSV & Load with Custom Columns

In [ ]:
import pandas as pd
import numpy as np
con = """101,Alice,25,Finance,85000
102,Bob,30,IT,92000
103,Charlie,22,Marketing,61000
104,Diana,28,IT,88000
105,Evan,35,Finance,95000"""

with open("data.csv","w") as f:
  f.write(con)

col = ["ID", "Name", "Age", "Department", "Salary"]
df1 = pd.read_csv("data.csv", header = None, names=col, index_col = 0)
df1

        Name  Age Department  Salary
ID
101    Alice   25    Finance   85000
102      Bob   30         IT   92000
103  Charlie   22  Marketing   61000
104    Diana   28         IT   88000
105     Evan   35    Finance   95000

Custom Delimiter (;) & Missing Values (-999 to NaN)

In [ ]:
sc = """ID;Val1;Val2;Val3
1;10.5;-999;100
2;-999;20.2;200
3;30.1;30.4;-999"""
with open("random.csv", "w") as f:
    f.write(sc)
df2 = pd.read_csv("random.csv", sep=";", na_values=-999)
df2

   ID  Val1  Val2   Val3
0   1  10.5   NaN  100.0
1   2   NaN  20.2  200.0
2   3  30.1  30.4    NaN

Read a Large CSV in Chunks & Compute Groupby Mean Across Chunks

In [ ]:
np.random.seed(42)
categories = ["A", "B", "C", "D","E"]
data = {
    "Category": np.random.choice(categories, size=10000),
    "Score": np.random.uniform(10, 100, size=10000)
}
pd.DataFrame(data).to_csv("large_data.csv", index=False)

chunk_size = 2000
totals = pd.Series(dtype=float)
counts = pd.Series(dtype=int)

for chunk in pd.read_csv("large_data.csv", chunksize=chunk_size):
    grouped = chunk.groupby("Category")["Score"]
    totals = totals.add(grouped.sum(), fill_value=0)
    counts = counts.add(grouped.count(), fill_value=0)
overall_mean = totals / counts

print("Overall Mean Per Category across all chunks:")
print(overall_mean)

Overall Mean Per Category across all chunks:
Category
A    54.775491
B    54.462881
C    55.648858
D    54.874352
E    55.341681
dtype: float64

Export to JSON (orient="records"), Read Back, and Check Equality

In [ ]:
df_original = pd.DataFrame({
    "A": [1, 2, 3],
    "B": ["apple", "banana", "cherry"]
})
json_str = df_original.to_json(orient="records")
print("JSON Output:\n", json_str)

df_reloaded = pd.read_json(json_str, orient="records")

is_equal = df_original.equals(df_reloaded)
print("\nAre the DataFrames equal using .equals()?", is_equal)

JSON Output:
 [{"A":1,"B":"apple"},{"A":2,"B":"banana"},{"A":3,"B":"cherry"}]

Are the DataFrames equal using .equals()? True

/tmp/ipykernel_2357/4053993660.py:8: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_reloaded = pd.read_json(json_str, orient="records")

Write HTML Table by Hand & Read with pd.read_html

In [ ]:
html_string = """
<table>
  <thead>
    <tr>
      <th>ProductID</th>
      <th>Product</th>
      <th>Price</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>P101</td>
      <td>Laptop</td>
      <td>1200</td>
    </tr>
    <tr>
      <td>P102</td>
      <td>Mouse</td>
      <td>25</td>
    </tr>
    <tr>
      <td>P103</td>
      <td>Keyboard</td>
      <td>75</td>
    </tr>
  </tbody>
</table>
"""

dfs_from_html = pd.read_html(html_string)
df_html = dfs_from_html[0]
df_html

/tmp/ipykernel_2357/3735256771.py:30: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  dfs_from_html = pd.read_html(html_string)

  ProductID   Product  Price
0      P101    Laptop   1200
1      P102     Mouse     25
2      P103  Keyboard     75

data loading and data storage

In [ ]:
# read data from csv and writing one into csv file
#txt  .txt to .csv file using delimiter and all

In [ ]:
#create text file and enter data | write  operation

with open (" Student.txt ", "w") as file:
  file.write("Name, Department, Marks, City \n"),
  file.write("Ishika, CSE, 98, Aligarh \n"),
  file.write("Disha, CSE, 92, Mathura \n"),
  file.write("Harshit, CSE, 84, Agra \n"),
  file.write("Tisha, Management, 95, Aligarh \n"),
  file.write("Bhoomika, CSE, 83, Ghaziaabad \n")

In [ ]:
with open("/content/ Student.txt ","r") as file:
  data = file.read()

print(data)

Name, Department, Marks, City
Ishika, CSE, 98, Aligarh
Disha, CSE, 92, Mathura
Harshit, CSE, 84, Agra
Tisha, Management, 95, Aligarh
Bhoomika, CSE, 83, Ghaziaabad

In [ ]:
#convert .txt data into .csv file
# import pandas as pd
# df = pd.read_csv("/content/ Student.txt ", sep = ",")
# df.to_csv("Student.csv", index=False)
# print(df)

import pandas as pd
df = pd.read_csv('/content/ Student.txt ')
df.to_csv('students.csv', index=False)
csv_df = pd.read_csv('students.csv')
display(csv_df)

       Name   Department   Marks         City
0    Ishika          CSE      98      Aligarh
1     Disha          CSE      92      Mathura
2   Harshit          CSE      84         Agra
3     Tisha   Management      95      Aligarh
4  Bhoomika          CSE      83   Ghaziaabad

In [ ]:
#pickle

df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 22],
    "City": ["New York", "San Francisco", "Los Angeles"]
})

In [ ]:
df

      Name  Age           City
0    Alice   25       New York
1      Bob   30  San Francisco
2  Charlie   22    Los Angeles

In [ ]:
#save dataframe into  pickle
pl = df.to_pickle("Students_pkl.pkl")

In [ ]:
#read the pickle
df_pickle = pd.read_pickle("Students_pkl.pkl")
df_pickle

      Name  Age           City
0    Alice   25       New York
1      Bob   30  San Francisco
2  Charlie   22    Los Angeles

web scraping

In [ ]:
import requests
from bs4 import BeautifulSoup
url = "https://www.amazon.com/"
page = requests.get(url)
soup = BeautifulSoup(page.text, "html.parser")

In [ ]:
print(soup.title.text)

Amazon.com. Spend less. Smile more.

parquet

In [ ]:
df_parquet = df_pickle
df_parquet.to_parquet("student_pqt.parquet",index= False)

In [ ]:
#read parquet file
df_parquet_file = pd.read_parquet("student_pqt.parquet")
df_parquet_file

      Name  Age           City
0    Alice   25       New York
1      Bob   30  San Francisco
2  Charlie   22    Los Angeles

sqlite

In [ ]:
import sqlite3
conn = sqlite3.connect("students.db")

In [ ]:
cursor = conn.cursor()

In [ ]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS students (
    Name TEXT,
    Age INTEGER,
    City TEXT
)


""")
print("Table created successfully")

Table created successfully

In [ ]:
conn = sqlite3.connect("students.db")
cursor = conn.cursor()
cursor.execute(
    "INSERT INTO students VALUES (?,?,?)",
    ("Amit", 101, "90")
)
conn.commit()
conn.close()
print("Insert successful and connection closed.")

Insert successful and connection closed.

In [ ]:
conn = sqlite3.connect("students.db")
conn.commit()
print("success")
conn.close()

success

In [ ]:
# retrieve | read the data
conn = sqlite3.connect("students.db")
cursor = conn.cursor()
cursor.execute("SELECT * FROM students")
rows = cursor.fetchall()
for row in rows:
  print(row)
conn.close()

('Amit', 101, '90')
('Amit', 101, '90')

In [ ]:
import sqlite3

conn = sqlite3.connect("stduents.db")
cursor = conn.cursor()
cursor.execute("DROP TABLE IF EXISTS student_table")

cursor.execute("""
CREATE TABLE student_table(
    NAME TEXT,
    ROLL_NO INTEGER,
    MARKS INTEGER
)
""")
cursor.execute("INSERT INTO student_table VALUES(?, ?, ?)", ("Ishika", 1, 99))
cursor.execute("INSERT INTO student_table VALUES('Disha', 14, 99)")
cursor.execute("INSERT INTO student_table VALUES('Harshit', 18, 100)")

conn.commit()

cursor.execute("SELECT * FROM student_table")
for row in cursor.fetchall():
    print(row)

conn.close()

('Ishika', 1, 99)
('Disha', 14, 99)
('Harshit', 18, 100)

31/10

In [1]:
import pandas as pd
import json

In [2]:
# Q1. Create CSV and display first 5 rows and info()
df = pd.DataFrame({
    'Roll No': range(1, 11),
    'Name': ['Amit','Priya','Rahul','Sneha','Vikas','Anjali','Rohit','Pooja','Karan','Neha'],
    'Branch': ['CSE','ECE','CSE','ME','ECE','CSE','ME','ECE','CSE','ME'],
    'Marks': [85, 90, 78, 92, 88, 76, 89, 91, 84, 80]
})
df.to_csv('students.csv', index=False)

df = pd.read_csv('students.csv')
print(df.head(5))
print(df.info())

   Roll No   Name Branch  Marks
0        1   Amit    CSE     85
1        2  Priya    ECE     90
2        3  Rahul    CSE     78
3        4  Sneha     ME     92
4        5  Vikas    ECE     88
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Roll No  10 non-null     int64
 1   Name     10 non-null     object
 2   Branch   10 non-null     object
 3   Marks    10 non-null     int64
dtypes: int64(2), object(2)
memory usage: 452.0+ bytes
None

In [3]:

# Q2. Read with header=None and names=[...] then index_col
df2 = pd.read_csv('students.csv', header=None, names=['Roll No','Name','Branch','Marks'])
print(df2)
df2 = pd.read_csv('students.csv', index_col='Roll No')
print(df2)

    Roll No    Name  Branch  Marks
0   Roll No    Name  Branch  Marks
1         1    Amit     CSE     85
2         2   Priya     ECE     90
3         3   Rahul     CSE     78
4         4   Sneha      ME     92
5         5   Vikas     ECE     88
6         6  Anjali     CSE     76
7         7   Rohit      ME     89
8         8   Pooja     ECE     91
9         9   Karan     CSE     84
10       10    Neha      ME     80
           Name Branch  Marks
Roll No
1          Amit    CSE     85
2         Priya    ECE     90
3         Rahul    CSE     78
4         Sneha     ME     92
5         Vikas    ECE     88
6        Anjali    CSE     76
7         Rohit     ME     89
8         Pooja    ECE     91
9         Karan    CSE     84
10         Neha     ME     80

In [4]:

# Q3. Handle missing values written as NA, - and blank
df3 = pd.read_csv('students.csv', na_values=['NA', '-', ''])
print(df3.isnull().sum())

Roll No    0
Name       0
Branch     0
Marks      0
dtype: int64

In [17]:

# Q4. Read only Name and Marks, and only first 5 rows
df4 = pd.read_csv('students.csv', usecols=['Name','Marks'], nrows=5)
print(df4)

    Name  Marks
0   Amit     85
1  Priya     90
2  Rahul     78
3  Sneha     92
4  Vikas     88

In [19]:
# Q5. Write without index, and write only Marks column
df.to_csv('new_students.csv', index=False)
df[['Marks']].to_csv('marks.csv', index=False)
print(df)

   Roll No    Name Branch  Marks
0        1    Amit    CSE     85
1        2   Priya    ECE     90
2        3   Rahul    CSE     78
3        4   Sneha     ME     92
4        5   Vikas    ECE     88
5        6  Anjali    CSE     76
6        7   Rohit     ME     89
7        8   Pooja    ECE     91
8        9   Karan    CSE     84
9       10    Neha     ME     80

In [20]:
# Q6. Load JSON with json.loads and convert to DataFrame, then export
with open('data.json', 'r') as f:
    data = json.loads(f.read())
df_json = pd.DataFrame(data)
print(df_json)
df_json.to_json('output.json', orient='records', indent=2)

   Roll No   Name Branch  Marks
0        1   Amit    CSE     85
1        2  Priya    ECE     90

In [21]:
# Q7. Read large CSV in chunks of 1000 and find average
total_sum = 0
total_count = 0
for chunk in pd.read_csv('large.csv', chunksize=1000):
    total_sum += chunk['Marks'].sum()
    total_count += chunk['Marks'].count()

avg = total_sum / total_count
print(f"Average: {avg}")

Average: 74.4319

In [22]:
import pandas as pd
import os

In [26]:
# Q9. Use read_html on Wikipedia page with custom User-Agent
url = 'https://en.wikipedia.org/wiki/List_of_countries_by_population'
storage_options = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)'}
tables = pd.read_html(url, storage_options=storage_options)
print(f"Total tables found: {len(tables)}")
df_wiki = tables[0]
print(df_wiki.head())

Total tables found: 3
        Location    Population % of world         Date  \
0          World  8.232000e+09       100%  13 Jun 2025
1          India  1.429404e+09      17.3%   1 Jul 2026
2          China  1.404890e+09      17.0%  31 Dec 2025
3  United States  3.417849e+08       4.1%   1 Jul 2025
4      Indonesia  2.901251e+08       3.5%  30 Jun 2026

  Source (official or from the United Nations) Notes
0                          UN projection[1][3]   NaN
1                       Official projection[4]   [b]
2                         Official estimate[5]   [c]
3                         Official estimate[6]   [d]
4                National annual projection[7]   NaN

In [28]:
# Q10. Pickle
df = pd.DataFrame({'A': [1,2,3], 'B': ['x','y','z']})
df.to_csv('data.csv', index=False)
df.to_pickle('data.pkl')
df_pickle = pd.read_pickle('data.pkl')
print(df_pickle)
csv_size = os.path.getsize('data.csv')
pkl_size = os.path.getsize('data.pkl')
print(f"CSV: {csv_size} bytes, Pickle: {pkl_size} bytes")

   A  B
0  1  x
1  2  y
2  3  z
CSV: 16 bytes, Pickle: 781 bytes

In [29]:
# Q11. Parquet / HDF5
df.to_parquet('data.parquet', index=False)
df_parquet = pd.read_parquet('data.parquet')
print(df_parquet)

   A  B
0  1  x
1  2  y
2  3  z

In [ ]:
# Q12. Why pickle not recommended?
# Answer: Pickle is Python-specific and insecure.
# 1. Executing arbitrary code on unpickling - malicious pickle can run code.
# 2. Not portable - version dependent, breaks across Python versions.
# 3. Not human-readable.
# Hence not for long-term storage or untrusted files.

In [31]:
# Q13. Fetch from public API
import requests

# Using a free, public JSON API instead of a Wikipedia HTML page
url = "https://jsonplaceholder.typicode.com/users"
response = requests.get(url)
print(f"Status Code: {response.status_code}")

if response.status_code == 200:
    data = response.json()
    print(f"First record: {data[0]}")
else:
    print("Failed to retrieve data")

Status Code: 200
First record: {'id': 1, 'name': 'Leanne Graham', 'username': 'Bret', 'email': 'Sincere@april.biz', 'address': {'street': 'Kulas Light', 'suite': 'Apt. 556', 'city': 'Gwenborough', 'zipcode': '92998-3874', 'geo': {'lat': '-37.3159', 'lng': '81.1496'}}, 'phone': '1-770-736-8031 x56442', 'website': 'hildegard.org', 'company': {'name': 'Romaguera-Crona', 'catchPhrase': 'Multi-layered client-server neural-net', 'bs': 'harness real-time e-markets'}}